#!/bin/bash

################ Variables

timestamp=$(date +"%Y-%m-%d %H:%M:%S")  ### sets timestamp as year/month/day hour:minutes:seconds

################ Script

# appends <timestamp temp hum> to register.txt where <temp> and <hum> are obtained by reading de DHT22
# sensor with the <dhtsensor.py> python script.

echo "$timestamp $(sudo /home/pi/sensor_log/./dhtsensor.py 22 4)" >> /home/pi/sensor_log/register.txt
